let csrf='', current=null, templates={}; const $=id=>document.getElementById(id);
function cookie(k){return document.cookie.split('; ').find(x=>x.startsWith(k+'='))?.split('=')[1]||''}
function payload(){return {scenario_id:$('scenario').value,source:$('source').value,destination:$('destination').value,bandwidth_mbps:+$('bandwidth_mbps').value,delay_ms:+$('delay_ms').value,loss_percent:+$('loss_percent').value,ping_count:+$('ping_count').value,iperf_duration_seconds:+$('iperf_duration_seconds').value,test:$('test').value,dry_run:$('dry_run').checked,confirmation:$('confirmation').value}}
async function api(path, method='GET', body){let o={method,headers:{}};if(method==='POST'){o.headers={'Content-Type':'application/json','X-CSRF-Token':csrf};o.body=JSON.stringify(body)}let r=await fetch(path,o);let j=await r.json();if(!r.ok)throw Error(j.error||r.status);return j}
function draw(t){let p=t.links.map(l=>`${l.source}—${l.target} (${l.bandwidth_mbps??20} Mbps, ${l.delay_ms??0} ms, ${l.packet_loss_percent??0}%)`).join('\n'),s=$('source').value,d=$('destination').value;$('topology').innerHTML='<h2>Local SVG topology</h2><svg viewBox="0 0 650 110">'+t.nodes.map((n,i)=>`<g><circle cx="${80+i*180}" cy="50" r="30" class="${n.role} ${n.id===s?'source':''} ${n.id===d?'destination':''}"/><text x="${60+i*180}" y="100">${n.id} (${n.role})${n.id===s?' • SOURCE':''}${n.id===d?' • DESTINATION':''}</text>${i?`<line x1="${50+i*180}" y1="50" x2="${110+(i-1)*180}" y2="50"/>`:''}</g>`).join('')+'</svg><pre>'+p+'</pre>'}
function endpoints(){let t=templates[$('scenario').value];$('source').innerHTML=t.endpoint_capable_nodes.map(x=>`<option>${x}</option>`).join('');$('destination').innerHTML=t.endpoint_capable_nodes.map(x=>`<option>${x}</option>`).join('');$('destination').selectedIndex=Math.min(1,$('destination').options.length-1);draw(t)}
async function poll(){if(!current)return;try{current=await api('/api/runs/'+current.run_id);$('status').textContent=JSON.stringify(current,null,2);if(['SUCCEEDED','FAILED','CANCELLED'].includes(current.status)){$('downloads').innerHTML=['json','csv','log','zip'].map(x=>`<a href="/api/runs/${current.run_id}/download/${x}">${x}</a>`).join(' | ');return}}catch(e){$('status').textContent=e}setTimeout(poll,800)}
async function boot(){let sys=await api('/api/system');csrf=sys.csrf_token||cookie('dt_csrf');let all=await api('/api/scenarios');all.scenarios.forEach(t=>templates[t.id]=t);$('scenario').innerHTML=all.scenarios.map(t=>`<option value="${t.id}">${t.display_name}</option>`).join('');endpoints();$('status').textContent='Ready. Docker available: '+sys.docker_available}
$('scenario').onchange=endpoints;$('source').onchange=() => draw(templates[$('scenario').value]);$('destination').onchange=() => draw(templates[$('scenario').value]);$('dry_run').onchange=()=>$('confirmWrap').hidden=$('dry_run').checked;$('validate').onclick=async()=>{$('status').textContent=JSON.stringify(await api('/api/validate','POST',payload()),null,2)};$('run').onclick=async()=>{current=await api('/api/runs','POST',payload());poll()};$('cancel').onclick=async()=>{if(current)await api('/api/runs/'+current.run_id+'/cancel','POST',{})};$('cleanup').onclick=async()=>{if(current)await api('/api/runs/'+current.run_id+'/cleanup','POST',{})};boot().catch(e=>$('status').textContent=e);
